name: Feature request
description: Describe a collecting problem and a possible improvement.
title: "[Feature]: "
body:
  - type: textarea
    id: problem
    attributes:
      label: What collecting problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed behavior and alternatives
    validations:
      required: true
